[project]
name = "msp-ice-flights-shiny"
version = "0.1.0"
requires-python = ">= 3.12.12"
dependencies = [
    "pyairtable>=2.3.3",
    "pandas>=3.0.0",
    "plotly>=6.5.2",
    "plotnine>=0.15.3",
    "shiny>=1.5.1",
    "shinyswatch>=0.9.0",
]
